### ISSUE TITLE
Configuration required for cordova app and launch

### ISSUE THREAD

**Issue by takhil** [adobe/cordova-acpsample#8]
We are new to the adobe analytics and using launch for our ionic Cordova app. According to documentation I was able to setup the adobe launch for web application and now struggling to implement for mobile app. I was not able to find the right steps to configure and documentation for the app as well as launch website can anyone help on this?

**Comment by rymorale** [comment]
Hi @takhil, the configuration documentation can be seen at https://aep-sdks.gitbook.io/docs/using-mobile-extensions/mobile-core/configuration#configure-with-the-experience-platform-launch-app-id. You would call the `configureWithAppId` API from your native code with the app id that you receive from launch.

Thanks,
Ryan Morales
Mobile Engineer
[Adobe Experience Cloud](https://www.adobe.com/experience-cloud.html)

**Comment by takhil** [comment]
Hi @rymorale,
thanks for quick response from the documentation and examples please confirm we can't use web launch property for Cordova apps. we have to create a mobile property from adobe launch and then use the specific environments id's for different apps?

If this is the case ionic Cordova commands build the app when we should update the adobe Id's in the process and is there any other documentation that can help me ? because ionic commands are generating apk and ipa for us with one command
I'm not sure when can we do this?

FYI -  we are using CI/CD to do all the builds. recommendations are much appreciated we are blocked because of this issue

**Comment by rymorale** [comment]
Hi @takhil, that is correct. For configurating a cordova app using the Adobe ACP SDK, a mobile property must be created on Adobe Launch for use in the app. The app id should be added to the native code generated by the Cordova commands. An example can be seen at the readme located at https://github.com/adobe/cordova-acpcore.

**Comment by takhil** [comment]
One more last question about the implementation, say if we add the native code for mobile  and <script> for web application.  I understood from the conversation we need different implementations for web and mobile to track analytics.

because we are using common code for web and mobile how the analytics tracking works I'm using data layer to track the web application data points will this be sufficient for mobile analytics. 

But this is direction we are into, Can you point us to right and best practices for the hybrid apps and proper implementation document I didn't find any documentation about this.

**Comment by rymorale** [comment]
Hi @takhil, the mobile application will need to use the MobileCore extension alongside the Analytics extension to send data to Analytics. The `trackAction` or `trackState` API are the API used to send data: https://aep-sdks.gitbook.io/docs/getting-started/initialize-the-sdk. 
As for your question regarding hybrid web and mobile apps, the cordova ACP mobile sdk's are for mobile applications only. They are not compatible with hybrid (web and mobile) apps.

**Comment by takhil** [comment]
@rymorale  - thanks for the response when it comes to Angular application the router is not triggering analytics it is only happening on page load. I added a rule (Library Load page Top) and then send beacon but it's still not working. i didn't find any documentation around this. If you point me to right documentation that will keep us moving. 

when I search for documentation it is redirecting to 
https://experienceleague.adobe.com/docs/experience-manager-64/developing/headless/spas/spa-launch.html?lang=en#headless

I'm sure this is not one I'm looking for

**Comment by rymorale** [comment]
Hi @takhil, I do not have experience with Adobe Analytics in an Angular app. There is a forum post regarding Angular + Analytics at https://experienceleaguecommunities.adobe.com/t5/adobe-analytics-discussions/adobe-analytics-implementation-for-angular-2-4-5-based-spa/td-p/258551 and the Angular plugin can be found at https://github.com/angulartics/angulartics-adobe-analytics. Hope this helps.

**Comment by bhandaribhuminpfizer** [comment]
@takhil I have implemented in an ionic application here is some useful code/steps for you : 

step 1: you may need to add a make file from the sample repo and run the command `make do-install` after adding ios and android platforms. **_!important_** **add plugins after platform add.**

In the package you may have these dependencies: 
 "devDependencies": {
    "@adobe/cordova-acpcore": "git+https://github.com/adobe/cordova-acpcore.git"
  }

For injection, you may use 

```
import * as ADB from '@adobe/cordova-acpcore/www/ACPCore';
...
...
...
ADB.trackState(state, data);

```

After that for app ID configuration you may go to > platform-> ios -> ProjectName -> Classes-> [AppDelegate.m](https://github.com/adobe/cordova-acpsample/blob/d4ed2fb376497f87ed6e03b793220fa856a71a07/TestApp/platforms/ios/HelloCordova/Classes/AppDelegate.m#L50)

Hope it helps 👍🏻
