### ISSUE TITLE
cordova platform add ios@6.2.0 getting 404

### ISSUE THREAD

**Issue by bhandaribhuminpfizer** [adobe/cordova-acpsample#9]
### Expected Behaviour

Platform added if run `cordova plugin add ios@6.2.0`

### Actual Behaviour

When trying to run `cordova plugin add ios@6.2.0` it failed at getting cordova-acpcore plugin add.

When Cordova is trying to get cordova-acpcore plugins it failed getting error 404

### Reproduce Scenario (including but not limited to)

1. cordova platform rm ios/android
2. rm -rf plugins/ platforms/
3. cordova platform add ios@6.2.0

#### Platform and Version

cordova-ios : 6.2.0

**cordova info**

  ```
Cordova Packages:

    cli: 10.0.0
        common: 4.0.2
        create: 3.0.0
        lib: 10.0.0
            common: 4.0.2
            fetch: 3.0.1
            serve: 4.0.0

Project Installed Platforms:

    ios: 6.2.0

Project Installed Plugins:

    cordova-plugin-device: 2.0.3
    cordova-plugin-whitelist: 1.3.4

Environment:

    OS: macOS 11.3.1 (20E241) (darwin 20.4.0) x64
    Node: v10.17.0
    npm: 6.11.3

ios Environment:

    xcodebuild:
Xcode 12.5.1
Build version 12E507

**Comment by rymorale** [comment]
Hi @bhandaribhuminpfizer, are you still seeing this issue? If not, can you try reinstalling cordova:
`sudo npm install -g cordova`
then trying to add the platform again?
I was seeing the same issue with the acpcore plugin being unable to be fetched and re-running the cordova install resolved it.

**Comment by bhandaribhuminpfizer** [comment]
@rymorale Thanks for helping `sudo npm install -g cordova` didn't work for me on the local system or I was trying to build using GIT-CI Automation. :(

**Comment by rymorale** [comment]
Hi @bhandaribhuminpfizer,

Did you setup a NPM access token on your git repo? If not, there is information available at https://docs.npmjs.com/creating-and-viewing-access-tokens.

Thanks,
Ryan

**Comment by bhandaribhumin** [comment]
Hi @rymorale my NPM access token already been configured, but still facing same issue.

**Comment by rymorale** [comment]
Hi @bhandaribhumin, 
Can you try adding the ACP plugins using the included Makefile? `make setup` should take care of the installation of the plugins with a fresh copy of the acpsample repo. Please let me know if you have any additional questions.

Thanks,
Ryan
